### ISSUE TITLE
Show tooltips on hover

### ISSUE THREAD

**Issue by vilardellsalles** [vilardellsalles/vilardellsalles.github.io#9]
It would be interesting to show the captions after media only when moving the mouse over the content. A possible starting point would be [CSS tooltips](https://www.w3schools.com/css/css_tooltip.asp) and [CSS combinators](https://www.w3schools.com/css/css_combinators.asp), but maybe Javascript would work better. An example CSS would be:

```css
.caption {
  display: none;
  text-align: justify;
  position: absolute;
  z-index: 1;
  right: 100%;
  margin: 1em;
  width: 25%;
}

img:hover + p.caption {
  display: inline-block;
}

video:hover + div.caption {
  display: inline-block;
}

div.bk-root:hover + div.caption {
  display: inline-block;
}
```

In this example tooltips are not always placed at the proper position. Sometimes tooltip starts at the top-left part of the image and sometimes start at the bottom-left.
